# Generated by Django 5.0.4 on 2024-04-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=255)),
                ('work_description', models.CharField(max_length=300)),
                ('work_image', models.ImageField(blank=True, upload_to='works/%Y/%m/%d')),
                ('work_date', models.DateTimeField(auto_now_add=True)),
                ('workers', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'OurWorks',
                'db_table': 'our_works',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d'),
        ),
    ]
