# Generated by Django 5.0.4 on 2024-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memeber_name', models.CharField(max_length=255)),
                ('memmber_added_date', models.DateTimeField()),
                ('member_president', models.CharField(max_length=255)),
                ('member_image', models.ImageField(blank=True, upload_to='member/')),
            ],
            options={
                'verbose_name': 'Members',
                'db_table': 'members',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_organizate_date', models.DateTimeField()),
                ('organization_president', models.CharField(max_length=255)),
                ('organization_logo', models.ImageField(blank=True, upload_to='organization/')),
            ],
            options={
                'verbose_name': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['id'],
            },
        ),
    ]
